services:
  - type: web
    name: telegram-webapp
    env: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        value: your_token_here  # можно оставить пустым, потом задашь в UI
